### ISSUE TITLE
Write cookbook entries

### ISSUE THREAD

**Issue by zimeon** [IIIF/api#1409]
* [x] tasty lasagne
 * [ ] Introductory editorial (how to use the specs and cookbook?)

The corresponding 2.1 test fixture(s) is given like this, where appropriate: .._(3,5)_  
Building a manifest in stages, adding more complexity at each stage
 
* [ ] Minimum Viable Manifest (1) (use static image as content resource, w.h)
* [ ] Minimum Viable Manifest (1) (use single audio as content resource, d)
* [ ] Minimum Viable Manifest (1) (use single video as content resource, w,h,d)
* [ ] Image different size to canvas (26)
* [ ] Image Service for single image (24,25)
* [ ] metadata and summary (2,5)
* [ ] Multiple values and languages (3,4,6)
* [ ] Multiple formats of strings (text, html, markdown...?) (64)
* [ ] Rights statement(s) (7)
* [ ] Book (simplest, > 1 canvas) (19)
* [ ] Book (viewingDirection variations) (11,12,13,14)
* [ ] Book (paging variations) (15,16,17) 
* [ ] thumbnail algorithm / discussion
* [ ] Alternative sequences, applications of (20,22,23)
* [ ] museum object (fwd ref to renderings)
* [ ] video - more complex examples
* [ ] audio - more complex examples 
* [ ] placeholderCanvas
* [ ] accompanyingCanvas
* [ ] start (65)

Textual and other supplementary content

* [ ] Transcription of image-based content - various examples gathered (43,44,45,46,47,48)
* [ ] Transcription of audio and video

Other kinds of annotations (leading on to segmentation examples later)

* [ ] comments - various examples (51,52,54)
* [ ] Fragment selectors (61)
* [ ] tagging
* [ ] hotspot linking
* [ ] Annotation in the context of a particular content resource https://github.com/IIIF/iiif-stories/issues/101

Internal structure

* [ ] table of contents (ranges) - book chapters
* [ ] table of contents (ranges) - articles in a newspaper
* [ ] table of contents (ranges) - acts of an opera
* [ ] Alternative Sequence (via `sequence` Range)
* [ ] `sequence` Range with partial canvases
* [ ] metadata on any resource (21)

Higher-level structure

* [ ] multi-volume work
* [ ] bound multi-volume work
* [ ] paged Collections (from #1343)

Segmentation and complex resources

* [ ] Choice (simplest) (28)
* [ ] Choice - multispectral flavoured example, with image services (29)
* [ ] foldouts, etc (Choice or non-paged interlude (flaps vs maps))? 
* [ ] Multiple images (master/detail) (30,31)
* [ ] Multiple images and multiple choices (32,33,34)
* [ ] basic segmentation (crop out scanner) (35,36,37,38)
* [ ] Image with CSS Rotation (39)
* [ ] Reusing an image service (ImageApiSelector) (41)
* [ ] non-rectangular segmentation
* [ ] temporal segmentation
* [ ] Audio only from video (and other xxxContentSelector scenarios)
* [ ] canvas on canvas (#1191)
* [ ] detail images 
* [ ] CSS styling 

Linking

* [ ] alternative representations (rendering (?))
* [ ] Linking from Image API to Presentation API (via partOf as per #600, #1507)
* [ ] Linking from Image API to external metadata
* [ ] Linking from external metadata to Image API
* [ ] Linking from external metadata to Presentation API
* [ ] Linking between Presentation API representations
* [ ] seeAlso scenarios (incl other manifests) (8)

Technical 

* [ ] extensions (18)
* [ ] services (9,10)
* [ ] Mixed version scenarios (Prezi 3+Image 2)
* [ ] Publishing v2 and v3 versions

Real-world complex objects (ideally taken from actual collections)

* [ ] An Image gallery
* [ ] A complex printed work with foldouts and choice
* [ ] A music album's audio resources
* [ ] ...and its image resoures
* [ ] ...combined to demonstrate _together_
* [ ] An opera on one Canvas
* [ ] An opera on multiple Canvases
* [ ] Adaptive bit rate AV examples
* [ ] A field recording
* [ ] A newspaper
* [ ] Example with extensions and services 
* [ ] A manuscript with multiple orderings
* [ ] a Sammelband
* [ ] Archival collection (hierarchy, paging)
* [ ] Thumbnail range for video navigation
* [ ] Video with captions in multiple languages
* [ ] Mixed Image Service references (a mashup, with img2 and img3 services)
* [ ] Glenn Gould - score and performance scenarios (transcribing)

Access Control (this might be in a separate auth cookbook)

* [ ] probe service for simple resource
* [ ] auth for adaptive bit rate media (MPEG-DASH)
* [ ] [Anyone can deep zoom, auth reqd for hi-res download](https://digirati-co-uk.github.io/iiif-auth-client/?image=https://iiifauth.digtest.co.uk/img/11_kitty_joyner.jpg/info.json)

**Comment by tomcrane** [comment]
TODO - triage https://github.com/IIIF/iiif-stories/issues for cookbook recipes

**Comment by sdellis** [comment]
please include "bound multi-volume work (i.e., Sammelband)" in the recipe list

**Comment by tomcrane** [comment]
@sdellis done!

**Comment by sdellis** [comment]
I think it would be good to also add a recipe for an annotation that targets only one image in a choice of images on a canvas. From what I understand this is possible now with Web Annotation? A number of people have expressed a need for this. Perhaps this could be added to the multispectral example in the list?

**Comment by sdellis** [comment]
Ah, excellent. Thanks! 👍

**Comment by mejackreed** [comment]
I'm up for collaborating on this, if there is in an interest in outside help.

**Comment by tomcrane** [comment]
There sure is! 👍

**Comment by regisrob** [comment]
Thinking about this after today's call... I have in mind a few real world use cases that could be used for some of the entries, and I think at least two of them are not already covered by the initial list of recipes:

- Canvas with a `facing-pages` behavior in a `paged` Manifest (map digitized as full spread in a manuscript)
- Range in an image-based Manifest which provides an alternate overview based on thumbnails (using the `thumbnail-nav` behavior); the use case is basically to be able to view as thumbnails the different "sections" of a collection of images gathered in a Manifest, e.g.: "in a Manifest gathering dozens of illuminations (coming from multiple manuscripts) that all share the same keyword/tag/descriptor (for instance "sultan"), show me in a grid view all the illuminations coming from a particular manuscript (e.g. "Français 2810")".

The second one may be regarded as too specific or too specialized... Anyway, I'm volunteering for these two entries if considered useful/relevant for the cookbook.

**Comment by tomcrane** [comment]
Candidate for rendering JSON examples:

https://ace.c9.io/

Can collapse blocks, highlight code.

**Comment by zimeon** [comment]
See https://github.com/IIIF/cookbook-recipes - moved work off into this reposiroty.
